export const cvStrongKeywords = [
  'cv',
  'resume',
  'curriculum vitae',
  'experience',
  'skills',
  'portfolio',
  'projects',
  'work history',
  'employment',
  'education',
  'certifications',
  'contact',
  'contacts',
  'phone',
  'email',
  'hire',
  'availability',
  'notice period',
  'location',
  'salary',
  'remote',
  'hybrid',
  'full time',
  'part time',
  'freelancer',
  'right to work',
  'javascript',
  'python',
  'react',
  'react native',
  'sql',
  'postgresql',
  'mongodb',
  'machine learning',
  'prompt engineering',
  'full stack',
  'frontend',
  'backend',
  'architecture',
  'database',
  'engineer',
  'developer',
  'mohammad',
  'mohamed',
];

export const cvWeakKeywords = [
  'about',
  'job',
  'position',
  'development',
  'programming',
  'ui',
  'user experience',
  'background',
  'languages',
  'strength',
  'stregnth',
  'weakness',
];

export const cvPatternKeywords = [
  /\bc\s*#\b/i,
  /\bc\+\+\b/i,
  /\bnode\.?js\b/i,
  /\bnext\.?js\b/i,
  /\bno\s*sql\b/i,
  /\bfront\s*end\b/i,
  /\bback\s*end\b/i,
  /\bfreelance(r)?\b/i,
  /\bm(u|o)hamm(a|e)d\b/i,
];

export const greetingKeywords = [
  'hi',
  'hello',
  'hey',
  'how are you',
  "what's up",
  'wass up',
  'how you doing',
  "what's going on",
  'are you good',
  'thanks',
  'thank you',
  'best regards',
  'have a good day',
  'nice day',
  'welcome',
  'sorry',
  'well done',
  'appreciate it',
  'good morning',
  'good evening',
  'good afternoon',
  'bye',
  'goodbye',
];
